---
arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv8l: 'armv8'

os_map:
  RedHat: 'rpm'
  Debian: 'deb'

arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
os_package: "{{ os_map[ansible_os_family] | default(ansible_os_family) }}"
