---
- name: Copy the nats systemd service file
  template:
    src: nats-server.service.j2
    dest: /etc/systemd/system/nats-server.service
    owner: root
    group: root
    mode: 0644
  notify: restart nats

- name: Copy the nats config file
  template:
    src: nats-server.conf.j2
    dest: "{{ nats_conf_dir }}/{{ nats_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart nats
