---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu-focal
    box: ubuntu/focal64
  # - name: centos-8
  #   box: centos/8
provisioner:
  name: ansible
verifier:
  name: ansible
